### ISSUE TITLE
[BUG] VideoCard와 GalleryPreview 수정 요청

### ISSUE THREAD

**Issue by chunzhi23** [SystemConsultantGroup/s-top-frontend#76]
## VideoCard
https://github.com/SystemConsultantGroup/s-top-frontend/blob/c0c06f21e4a1991d4bf302639404c1cda4384755/src/components/common/VideoCard/VideoCard.tsx#L1-L3
useEffect hook이 사용되었기에 "use client"를 상단에 작성해주어야 했습니다.
이 문제를 수정하는 겸사 바꾸면 좋을 다른 코드가 있어 남깁니다.

해당 코드에서 useEffect을 사용하지 않아도 될 것 같습니다.
이미 bookmarked를 state로 선언했기에 따로 설정이 필요하지 않을 듯 합니다.

https://github.com/SystemConsultantGroup/s-top-frontend/blob/c0c06f21e4a1991d4bf302639404c1cda4384755/src/components/common/VideoCard/VideoCard.tsx#L18-L26

그리고 #54 수정과 같이 내부에서 state를 선언하는 것이 아니라 외부에서 props로 bookmarked 변수와 handler 함수를 넘겨받고 그걸 사용하는 게 좋아 보입니다. API 연결할 때 페이지에서 handler 코드를 더 수정할 일이 발생할 수 있기 때문입니다.

## GalleryPreview
https://github.com/SystemConsultantGroup/s-top-frontend/blob/c0c06f21e4a1991d4bf302639404c1cda4384755/src/components/common/GalleryPreview/GalleryPreview.tsx#L21-L25
```
 ⨯ src\components\common\GalleryPreview\GalleryPreview.tsx (21:32) @ useMantineTheme
 ⨯ TypeError: (0 , _barrel_optimize_names_Card_CardSection_Flex_Text_useMantineColorScheme_useMantineTheme_mantine_core__WEBPACK_IMPORTED_MODULE_3__.useMantineTheme) is not a function
    at GalleryPreview (./src/components/common/GalleryPreview/GalleryPreview.tsx:23:168)
    at stringify (<anonymous>)
    at stringify (<anonymous>)
    at stringify (<anonymous>)
digest: "2894967837"
  19 |
  20 | export function GalleryPreview({ imgUrl, title, date, viewCount }: Props) {
> 21 |   const theme = useMantineTheme();
     |                                ^
  22 |   const { colorScheme } = useMantineColorScheme();
  23 |
  24 |   // text color와 맞추기
```
해당 부분에서 오류가 발생하여 확인 후 수정 부탁드리겠습니다!
색상을 위한 코드라면 theme/AppTheme.ts에 정리되어 있으니 module.css로 대신하는 것이 좋을 것 같습니다.

### Reproduction 🏗️

1. VideoCard - useEffect 삭제 및 state와 handler props로 받아오기
2. GalleryPreview - color theme 수정

### CheckList ✔️

- [X] 관련 Issue 가 이미 존재하는 지 확인해보셨나요?

**Comment by moony1204** [comment]
갤러리 프리뷰는 제가 작업한 게 아니고 mantine을 많이 안다뤄봐서..! 일단 확인은 해보겠습니다ㅜㅎㅎ 아마 @sera2002 님이 갤러리 프리뷰 작업하신 것 같습니다

**Comment by chunzhi23** [comment]
> 갤러리 프리뷰는 제가 작업한 게 아니고 mantine을 많이 안다뤄봐서..! 일단 확인은 해보겠습니다ㅜㅎㅎ 아마 @sera2002 님이 갤러리 프리뷰 작업하신 것 같습니다

앗 그렇군요..! 감사합니당
